contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #quantifyprotein channel"
    url: https://nfcore.slack.com/channels/quantifyprotein
    about: Discussion about the nf-core/quantifyprotein pipeline
